name: CD

on:
  push:
    branches:
      - staging
      - dev
  pull_request:
    branches:
      - staging
      - dev

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as needed
      
    - name: Deploy to staging
      run: |
        echo "Deploying to staging"
      # python deploy.py --environment staging  # Adjust script name and arguments as needed

  deploy_production:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as needed
      
    - name: Deploy to production
      run: |
        echo "Deploying to main branch (production)"
      # python deploy.py --environment production  # Adjust script name and arguments as needed