name: CI

on:
  push:
    branches:
      - staging  # Adjust branch name as needed
      - dev
  pull_request:
    branches:
      - staging  # Adjust branch name as needed
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as needed
      
    - name: Run tests
      run: |
        echo "Running tests"
      # python -m pytest tests/  # Adjust test directory as needed
      
    # - name: Lint code
    #   run: |
    #     pip install pylint
    #     flake8 .  # Adjust directory to lint as needed
      
    - name: Train model
      run: |
        echo "Train model"
      # python train_model.py  # Adjust script name as needed